-- Create payments table for Razorpay integration
-- Author: E-Commerce Development Team
-- Version: 1.0.0

CREATE TABLE payments (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    
    payment_id VARCHAR(255) NOT NULL UNIQUE,
    razorpay_order_id VARCHAR(255) NOT NULL,
    razorpay_payment_id VARCHAR(255),
    razorpay_signature TEXT,
    
    amount DECIMAL(10, 2) NOT NULL,
    currency VARCHAR(3) NOT NULL DEFAULT 'INR',
    
    status VARCHAR(50) NOT NULL,
    payment_method VARCHAR(50),
    
    user_id BIGINT NOT NULL,
    order_id BIGINT NOT NULL,
    
    receipt VARCHAR(255),
    description TEXT,
    error_code VARCHAR(100),
    error_description TEXT,
    
    paid_at TIMESTAMP NULL,
    failed_at TIMESTAMP NULL,
    refunded_at TIMESTAMP NULL,
    refund_amount DECIMAL(10, 2),
    refund_id VARCHAR(255),
    
    CONSTRAINT fk_payments_user_id FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_payments_order_id FOREIGN KEY (order_id) REFERENCES orders(id),
    
    INDEX idx_payments_payment_id (payment_id),
    INDEX idx_payments_razorpay_order_id (razorpay_order_id),
    INDEX idx_payments_razorpay_payment_id (razorpay_payment_id),
    INDEX idx_payments_user_id (user_id),
    INDEX idx_payments_order_id (order_id),
    INDEX idx_payments_status (status),
    INDEX idx_payments_created_at (created_at)
);

-- Add comments for documentation
ALTER TABLE payments 
  COMMENT = 'Payment transactions table for Razorpay integration';

ALTER TABLE payments 
  MODIFY COLUMN payment_id VARCHAR(255) NOT NULL UNIQUE
  COMMENT 'Unique payment identifier generated by the system';

ALTER TABLE payments 
  MODIFY COLUMN razorpay_order_id VARCHAR(255) NOT NULL
  COMMENT 'Razorpay order ID returned from create order API';

ALTER TABLE payments 
  MODIFY COLUMN razorpay_payment_id VARCHAR(255)
  COMMENT 'Razorpay payment ID returned after successful payment';

ALTER TABLE payments 
  MODIFY COLUMN razorpay_signature TEXT
  COMMENT 'Razorpay signature for payment verification';

ALTER TABLE payments 
  MODIFY COLUMN amount DECIMAL(10, 2) NOT NULL
  COMMENT 'Payment amount in the specified currency';

ALTER TABLE payments 
  MODIFY COLUMN currency VARCHAR(3) NOT NULL DEFAULT 'INR'
  COMMENT 'Payment currency code (ISO 4217)';

ALTER TABLE payments 
  MODIFY COLUMN status VARCHAR(50) NOT NULL
  COMMENT 'Payment status: CREATED, PROCESSING, PAID, FAILED, REFUNDED, CANCELLED, PENDING';

ALTER TABLE payments 
  MODIFY COLUMN payment_method VARCHAR(50)
  COMMENT 'Payment method used: RAZORPAY_CARD, RAZORPAY_UPI, etc.';

ALTER TABLE payments 
  MODIFY COLUMN receipt VARCHAR(255)
  COMMENT 'Receipt number for the payment';

ALTER TABLE payments 
  MODIFY COLUMN description TEXT
  COMMENT 'Payment description or notes';

ALTER TABLE payments 
  MODIFY COLUMN error_code VARCHAR(100)
  COMMENT 'Error code if payment failed';

ALTER TABLE payments 
  MODIFY COLUMN error_description TEXT
  COMMENT 'Error description if payment failed';

ALTER TABLE payments 
  MODIFY COLUMN paid_at TIMESTAMP NULL
  COMMENT 'Timestamp when payment was successfully completed';

ALTER TABLE payments 
  MODIFY COLUMN failed_at TIMESTAMP NULL
  COMMENT 'Timestamp when payment failed';

ALTER TABLE payments 
  MODIFY COLUMN refunded_at TIMESTAMP NULL
  COMMENT 'Timestamp when payment was refunded';

ALTER TABLE payments 
  MODIFY COLUMN refund_amount DECIMAL(10, 2)
  COMMENT 'Amount refunded for this payment';

ALTER TABLE payments 
  MODIFY COLUMN refund_id VARCHAR(255)
  COMMENT 'Refund ID from Razorpay'; 